

package userinterface.RestaurantAdminRole;


import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem eco;
    UserAccount account;
    String unique;
    Restaurant h;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,EcoSystem eco) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.eco = eco;
        this.account=account;
        unique=account.getEmployee().getName();
        System.out.print(unique);
        
        for(Restaurant r:eco.getRestaurantDirectory().getRestaurantList())
          {  System.out.print(r.getRestName());
        if(unique.equals(r.getRestName())){
            h=r;
            String s=r.getRestName();
        valueLabel.setText(s);
        
    }
        }
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMngInfo = new javax.swing.JButton();
        manageMenu = new javax.swing.JButton();
        manageOrders = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.activeCaption);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("My Work Area -Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        btnMngInfo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnMngInfo.setText("Manage Restaurant Info");
        btnMngInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngInfoActionPerformed(evt);
            }
        });
        add(btnMngInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, 460, 90));

        manageMenu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        manageMenu.setText("Manage Menu");
        manageMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMenuActionPerformed(evt);
            }
        });
        add(manageMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 450, 90));

        manageOrders.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        manageOrders.setText("Manage Orders");
        manageOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersActionPerformed(evt);
            }
        });
        add(manageOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 450, 80));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Welcome to Restaurant :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 250, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 350, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngInfoActionPerformed
        // TODO add your handling code here:
        ViewRestaurant panel = new ViewRestaurant(userProcessContainer,eco,h,account);
            userProcessContainer.add("ViewRestaurant",panel);
            CardLayout layout =(CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnMngInfoActionPerformed

    private void manageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMenuActionPerformed
       ManageMenu mm = new ManageMenu(userProcessContainer, eco,unique);
       userProcessContainer.add("ManageMenu",mm);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageMenuActionPerformed

    private void manageOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersActionPerformed
        ManageOrder mo = new ManageOrder(userProcessContainer,account, eco,unique);
        userProcessContainer.add("ManageOrder",mo);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrdersActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngInfo;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageMenu;
    private javax.swing.JButton manageOrders;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
